[package]
name = "rust_minp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust_minp"
path = "src/main.rs"

[lib]
name = "rust_minp"
path = "src/lib/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
